INSERT INTO attractions (id, description, elevation, name, type, country_id) VALUES
(1, 'An ancient Incan city located in the Andes mountains', 2430, 'Machu Picchu', 'historical site', 134),
(2, 'A massive statue of Jesus Christ overlooking Rio de Janeiro', 710, 'Christ the Redeemer', 'monument', 24),
(3, 'A large series of waterfalls', 195, 'Iguazu Falls', 'natural wonder', 7),
(4, 'The world''s largest salt flat', 3656, 'Salar de Uyuni', 'natural wonder', 21),
(5, 'A unique volcanic archipelago known for diverse wildlife', 0, 'Galapagos Islands', 'natural reserve', 50),
(6, 'The driest desert in the world', 2400, 'Atacama Desert', 'desert', 35),
(7, 'The world''s tallest uninterrupted waterfall', 979, 'Angel Falls', 'waterfall', 190),
(8, 'A stunning national park in Patagonia with mountains, glaciers, and lakes', 2800, 'Torres del Paine', 'national park', 35),
(9, 'A stunning basilica in Bogota', 2640, 'La Sagrada Familia', 'religious building', 37),
(10, 'The largest lake in South America', 3812, 'Lake Titicaca', 'lake', 21),
(11, 'A unique desert landscape with rock formations and sand dunes', 2500, 'Valley of the Moon', 'natural wonder', 35),
(12, 'An ancient city in the mountains', 1200, 'Ciudad Perdida', 'historical site', 37),
(13, 'An eerie collection of old train cars in the desert', 3665, 'Uyuni Train Cemetery', 'museum', 21),
(14, 'A beach with red sand cliffs', 0, 'Canoa Quebrada', 'beach', 24),
(15, 'A massive advancing glacier in Patagonia', 1500, 'Perito Moreno Glacier', 'glacier', 7),
(16, 'An ancient Mesoamerican city with large pyramids', 2300, 'Teotihuacan', 'archaeological site', 109),
(17, 'A large Mayan archaeological site', 300, 'Tikal', 'archaeological site', 68),
(18, 'A majestic active volcano', 5897, 'Cotopaxi', 'volcano', 50),
(19, 'A famous beach in Rio de Janeiro', 0, 'Copacabana Beach', 'beach', 24),
(20, 'The iconic Moai statues of Easter Island', 0, 'Rapa Nui', 'archaeological site', 35),
(21, 'One of the largest hydroelectric dams in the world', 220, 'Itaipu Dam', 'hydroelectric dam', 24),
(22, 'The highest mountain in the Americas, located in the Andes', 6960, 'Aconcagua', 'mountain', 7),
(23, 'Ancient geoglyphs etched into the southern desert', 520, 'Nazca Lines', 'archaeological site', 134),
(24, 'An ancient Mayan city located in the jungles', 500, 'Caracol', 'archaeological site', 18),
(25, 'A group of islands known for their pristine beaches and indigenous culture', 0, 'San Blas Islands', 'beach', 131),
(26, 'A tropical cloud forest reserve', 1600, 'Monteverde Cloud Forest', 'nature reserve', 41),
(27, 'A group of small islands off the northern coast', 0, 'Cayos Cochinos', 'beach', 73),
(28, 'A beautiful crater lake surrounded by volcanoes', 1560, 'Lake Atitlan', 'lake', 68),
(29, 'An underground Roman Catholic church built within the tunnels of a salt mine', 2650, 'Salt Cathedral of Zipaquira', 'religious building', 37),
(30, 'A tropical rainforest', 1050, 'El Yunque National Forest', 'national park', 138),
(31, 'A scenic region known for waterfalls and rainforests', 350, 'Tarapoto', 'natural wonder', 134),
(32, 'A beautiful coastal city with a rich colonial history', 0, 'La Guaira', 'city', 190),
(33, 'An ancient Mayan site known for its stunning sculptures', 600, 'Ruins of Copan', 'archaeological site', 73),
(34, 'A unique phenomenon where a saltwater lake turns pink', 0, 'The Pink Sea', 'natural wonder', 37),
(35, 'An active volcano with a massive crater lake', 2708, 'Poas Volcano', 'volcano', 41),
(36, 'A flat-topped mountain on the border between three countries', 2810, 'Mount Roraima', 'mountain', 190),
(37, 'A giant sculpture of a hand emerging from the sand on a beach', 0, 'La Mano de Punta del Este', 'sculpture', 186),
(38, 'A UNESCO World Heritage Site known for its stunning glaciers', 200, 'Los Glaciares National Park', 'national park', 7),
(39, 'A stunning coral archipelago and national park off the coast', 0, 'Los Roques Archipelago', 'national park', 190),
(40, 'One of the oldest civilizations in the Americas, an ancient city', 350, 'Caral', 'archaeological site', 134),
(41, 'The tallest waterfall in Ecuador, located in the Amazon rainforest', 150, 'San Rafael Waterfall', 'waterfall', 50),
(42, 'A remote archipelago and UNESCO World Heritage site known for its biodiversity', 0, 'Fernando de Noronha', 'natural reserve', 24),
(43, 'A mountain in Argentina with a striking array of colored stripes', 4175, 'Cerro de los Siete Colores', 'natural wonder', 7),
(44, 'The highest mountain in Ecuador, with a peak that is the farthest point from the Earth''s center', 6263, 'Chimborazo', 'mountain', 50),
(45, 'An underground river and cave system in the Yucatan Peninsula', 0, 'Rio Secreto', 'natural wonder', 109),
(46, 'A group of small, uninhabited islands off the coast of Mexico, known for their hidden beach', 0, 'Marieta Islands', 'beach', 109),
(47, 'The world''s largest tropical wetland', 100, 'Pantanal', 'wetland', 24),
(48, 'A wildlife reserve in Argentina famous for its large colony of Magellanic penguins', 0, 'Punta Tombo', 'wildlife reserve', 7),
(49, 'A shallow salt lake in Bolivia famous for its red water and flamingos', 4278, 'Laguna Colorada', 'lake', 21),
(50, 'A complex of salt evaporation ponds dating back to Incan times', 3000, 'Salt Flats of Maras', 'historical site', 134);
