services:
  n8n:
    image: n8nio/n8n:1.123.28
    container_name: softuni_ai_n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:


networks:
  default:
    name: softuni.ai
